@backend = http://localhost:3000
@testEmail = test@example.com
@testPassword = password123

### Check backend

GET {{backend}}/health

### Create user
# @name createUser

POST {{backend}}/signup
Content-Type: application/json

{
  "email": "{{testEmail}}",
  "password": "{{testPassword}}"
}

### Make login
# @name login

POST {{backend}}/users/login
Content-Type: application/json

{
  "email": "{{testEmail}}",
  "password": "{{testPassword}}"
}

### Get authenticated user

GET {{backend}}/auth/me

### Logout

POST {{backend}}/auth/logout

### Get how to play 

GET {{backend}}/how-to-play/scar

### Get how to play in spanish

GET {{backend}}/how-to-play/scar?lang=es

### Get villains

GET {{backend}}/villains

### Get villains in spanish

GET {{backend}}/villains?lang=es

### Get villain by id

GET {{backend}}/villains/captain-hook

### Get villain by id in spanish

GET {{backend}}/villains/scar?lang=es

### Get card by id

GET {{backend}}/cards/injustice

### Get card by id

GET {{backend}}/cards/injustice?lang=es

### GET translations by keys

GET {{backend}}/translations/es?namespace=homePage

### Get several translations by keys

GET {{backend}}/translations/es?namespace=homePage,cardTypes

### Get French translations

GET {{backend}}/translations/fr?namespace=homePage,howToPage,cardTypes,decks,actions

### Get villains in French

GET {{backend}}/villains?lang=fr

### Get villain by id in French

GET {{backend}}/villains/captain-hook?lang=fr

### Get card by id in French

GET {{backend}}/cards/injustice?lang=fr

### Get how to play in French

GET {{backend}}/how-to-play/scar?lang=fr
